### ISSUE TITLE
EFL, testing with pretrained models(YOLOX-M*) got AP 0

### ISSUE THREAD

**Issue by EthanChen1234** [ModelTC/EOD#20]
hi, I'm testing the pretrained models of EFL.

1) Improved Baseline Series
![image](https://user-images.githubusercontent.com/45474996/169195090-1dcce25d-96ec-47bd-9bec-1fbe24ecccb3.png)
the results is ok.

2) YOLOX* Series
![image](https://user-images.githubusercontent.com/45474996/169195279-8ff1b5a6-bb66-4bc4-9288-3023299b3efd.png)
the ap_iou 0.5 is 0.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/45474996/169195415-38a716fd-542d-44ea-b659-39de25698900.png">
And, I double checked that the model is well loaded the pretrained model.

the attached is the config yaml
[test-yaml.zip](https://github.com/ModelTC/EOD/files/8723153/test-yaml.zip)

In addition, the following modify added to avoid running error.
![image](https://user-images.githubusercontent.com/45474996/169196163-2537e1f3-62a8-4573-a3a6-18a0bfe14ef5.png)

**Comment by waveboo** [comment]
Hi @EthanChen1234 , thanks for you point out these bugs.

**Comment by waveboo** [comment]
Hi @EthanChen1234 , thanks for you pointing out the problems.

For the first question about the evaluation of the YOLOX* series. It is a logical problem of the 'pretrain_model' configs. You could **use 'resume_model: you_file_path.pth' as an alternative**. Or you can just **remove the 'ema' configs** in the yaml file if you do not need them.

For the second question, it is a bug about the version upgrade, you could just replace the file with the one: [roi_predictor.py.zip](https://github.com/ModelTC/EOD/files/8727884/roi_predictor.py.zip)

We will fix these bugs as soon as possible in the next EOD version. And thank you for your interest in EOD.
