### ISSUE TITLE
Any way to load original yolov5 series model ?

### ISSUE THREAD

**Issue by Stephenfang51** [ModelTC/EOD#4]
Hi, 

Just wonder if we can load original custom pretrained yolov5(s~x) model using your work?

or any way? if so, I suggest updating an easy example.

Thanks your great work !

**Comment by Joker-co** [comment]
Hi, thanks for your attention.
Original yolov5 models can't be loaded directly now. 
If you want to load, you must rename parameters in yolov5 model.
We will consider adding yolov5 head in the future.
